# Instalação e importação das bibliotecas

Instalação das bibliotecas se necessário

In [ ]:
!pip install numpy pandas matplotlib seaborn

Import bibliotecas com alias convencionais.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# EDA

## Carregando dados
Utilização da biblioteca pandas para leitura dos dados

In [4]:
df_salarios = pd.read_csv(r'./Dados/Salarios_dep_carg_query_1.csv')
df_media_salario = pd.read_csv(r'./Dados/Media_salarios_dep_carg.csv')
df_salario_localizacao = pd.read_csv(r'./Dados/Salarios_localizacao_query_2.csv')
df_media_salario_localizacao = pd.read_csv(r'./Dados/Media_salarios_localizacao.csv')

Prévisualização dos dados para conferencia da importação correta

In [9]:
df_salarios.head(10)

  DEPARTAMENTO                         CARGOS  SALARIO
0    Executive                      President    24000
1    Executive  Administration Vice President    17000
2    Executive  Administration Vice President    17000
3        Sales                  Sales Manager    14000
4        Sales                  Sales Manager    13500
5    Marketing              Marketing Manager    13000
6      Finance                Finance Manager    12008
7   Accounting             Accounting Manager    12008
8        Sales                  Sales Manager    12000
9        Sales           Sales Representative    11500

In [6]:
df_media_salario

        DEPARTAMENTO                           CARGOS  MÉDIA_SALARIAL
0          Executive                        President    24000.000000
1          Executive    Administration Vice President    17000.000000
2          Marketing                Marketing Manager    13000.000000
3              Sales                    Sales Manager    12200.000000
4         Accounting               Accounting Manager    12008.000000
5            Finance                  Finance Manager    12008.000000
6         Purchasing               Purchasing Manager    11000.000000
7   Public Relations  Public Relations Representative    10000.000000
8              Sales             Sales Representative     8396.551724
9         Accounting                Public Accountant     8300.000000
10           Finance                       Accountant     7920.000000
11          Shipping                    Stock Manager     7280.000000
12   Human Resources   Human Resources Representative     6500.000000
13         Marketing         Marketing Representative     6000.000000
14                IT                       Programmer     5760.000000
15    Administration         Administration Assistant     4400.000000
16          Shipping                   Shipping Clerk     3215.000000
17          Shipping                      Stock Clerk     2785.000000
18        Purchasing                 Purchasing Clerk     2780.000000

In [10]:
df_salario_localizacao.head(10)

,DEPARTAMENTO,CARGOS,CIDADE,PAIS,REGIAO,MEDIA_SALARIAL
0,Executive,President,Seattle,United States of America,Americas,24000
1,Executive,Administration Vice President,Seattle,United States of America,Americas,17000
2,Executive,Administration Vice President,Seattle,United States of America,Americas,17000
3,Sales,Sales Manager,Oxford,United Kingdom of Great Britain and Northern I...,Europe,14000
4,Sales,Sales Manager,Oxford,United Kingdom of Great Britain and Northern I...,Europe,13500
5,Marketing,Marketing Manager,Toronto,Canada,Americas,13000
6,Finance,Finance Manager,Seattle,United States of America,Americas,12008
7,Accounting,Accounting Manager,Seattle,United States of America,Americas,12008
8,Sales,Sales Manager,Oxford,United Kingdom of Great Britain and Northern I...,Europe,12000
9,Sales,Sales Representative,Oxford,United Kingdom of Great Britain and Northern I...,Europe,11500

In [8]:
df_media_salario_localizacao

,DEPARTAMENTO,CARGOS,CIDADE,PAIS,REGIAO,MEDIA_SALARIAL
0,Executive,President,Seattle,United States of America,Americas,24000.00
1,Executive,Administration Vice President,Seattle,United States of America,Americas,17000.00
2,Marketing,Marketing Manager,Toronto,Canada,Americas,13000.00
3,Sales,Sales Manager,Oxford,United Kingdom of Great Britain and Northern I...,Europe,12200.00
4,Accounting,Accounting Manager,Seattle,United States of America,Americas,12008.00
5,Finance,Finance Manager,Seattle,United States of America,Americas,12008.00
6,Purchasing,Purchasing Manager,Seattle,United States of America,Americas,11000.00
7,Public Relations,Public Relations Representative,Munich,Germany,Europe,10000.00
8,Sales,Sales Representative,Oxford,United Kingdom of Great Britain and Northern I...,Europe,8396.55
9,Accounting,Public Accountant,Seattle,United States of America,Americas,8300.00
10,Finance,Accountant,Seattle,United States of America,Americas,7920.00
11,Shipping,Stock Manager,South San Francisco,United States of America,Americas,7280.00
12,Human Resources,Human Resources Representative,London,United Kingdom of Great Britain and Northern I...,Europe,6500.00
13,Marketing,Marketing Representative,Toronto,Canada,Americas,6000.00
14,IT,Programmer,Southlake,United States of America,Americas,5760.00
15,Administration,Administration Assistant,Seattle,United States of America,Americas,4400.00
16,Shipping,Shipping Clerk,South San Francisco,United States of America,Americas,3215.00
17,Shipping,Stock Clerk,South San Francisco,United States of America,Americas,2785.00
18,Purchasing,Purchasing Clerk,Seattle,United States of America,Americas,2780.00